### PR TITLE
A command-line interface for Qthid

### PR DESCRIPTION
**Pull request by tstranex**
Hi Alexandru

I needed a command-line controller for the FCD so I wrote this small addition to Qthid. It's potentially useful to others so perhaps it can be included in the main branch. Please let me know what you think.

Regards,
Timothy

### CODE REVIEW

**Comment by csete** [comment]
Hi Timothy,

Thanks for the submission. I will consider it for the next release.
A few notes for future reference:

(1) Normally we don't modify the hidapi files within qthid as they are maintained as a separate project. Changes should be applied upstream and updated files are fetched and included in qthid regularly, see https://github.com/signal11/hidapi
(2) Qthid no longer uses the libusb backend because there were problems on recent linux distributions that come with libusb-1.0.9. We use the hidraw backend instead.

**Comment by dl1mx** [comment]
Hi Alex,

is there any work on a command line interface? I tried to compile it under Ubuntu 12.10 but I only get cast errors. Also tried to switch to hidraw, but no better compilation. I'm not a c or c++ specialist.

73 de Marco

**Comment by tstranex** [comment]
Hi Marco

Are you using the FCD Pro+ branch of my patch? I think I fixed the cast
errors there.
https://github.com/tstranex/qthid/tree/fcdpp

Regards,
Timothy

**Comment by csete** [comment]
Marco,

I don't understand your logic: Why do you think that a command line wrapper
around qthid would solve your problem? You would still need to build qthid
- some additional code.

Which version are you trying to compile? The hidraw backend has been the
default for a long time now and most certainly is in version 4.0 and 4.1.
Anyway, pretty much all versions of qthid should build without problem on
all version of Ubuntu since 10.04, but I can't help you if you don't post
any error messages. I recommend you try either the Funcube or FCD Pro+
yahoo groups depending on which dongle you have.

Alex

**Comment by csete** [comment]
Timothy,

I am going to close this pull request because the current plan is to finish libfcd (see https://github.com/jrcutler/libfcd) and include a command line tool in there. Qthid will then be migrated to use libfcd, but the point is that libfcd will contain a command line tool that will not require Qt as dependency.  I hope it's okay with you.

Alex

**Comment by dl1mx** [comment]
Hi Timothy,

I tried the following procedure:

git clone https://github.com/tstranex/qthid.git
cd qthid
git checkout fcdpp
qmake qthid.pro
make
./qthid   --> works fine with Funcube Pro Plus
cd cli
make

then I get these errors:

g++ `pkg-config libusb-1.0 --cflags` -I.. -Wall `pkg-config libusb-1.0 --libs` 
-o qthid-cli main.cpp ../fcd.c ../hid-libusb.c
../hid-libusb.c:26:0: Warnung: »_GNU_SOURCE« redefiniert [standardmäßig aktiviert]
<Kommandozeile>:0:0: Anmerkung: dies ist die Stelle der vorherigen Definition
../hid-libusb.c: In Funktion »hid_device\* new_hid_device()«:
../hid-libusb.c:121:48: Fehler: ungültige Umwandlung von »void_« in »hid_device_ 
{aka hid_device__}« [-fpermissive]
../hid-libusb.c: In Funktion »hid_device_info_ hid_enumerate(short unsigned int, 
short unsigned int)«:
../hid-libusb.c:482:54: Fehler: ungültige Umwandlung von »void_« in 
»hid_device_info_« [-fpermissive]
../hid-libusb.c: In Funktion »void read_callback(libusb_transfer_)«:
../hid-libusb.c:648:30: Fehler: ungültige Umwandlung von »void_« in »hid_device\* 
{aka hid_device__}« [-fpermissive]
../hid-libusb.c:653:49: Fehler: ungültige Umwandlung von »void_« in 
»input_report_« [-fpermissive]
../hid-libusb.c:654:45: Fehler: ungültige Umwandlung von »void_« in »uint8_t\* 
{aka unsigned char_}« [-fpermissive]
../hid-libusb.c: In Funktion »void_ read_thread(void_)«:
../hid-libusb.c:712:20: Fehler: ungültige Umwandlung von »void_« in »hid_device\* 
{aka hid_device__}« [-fpermissive]
../hid-libusb.c:717:21: Fehler: ungültige Umwandlung von »void_« in »unsigned 
char_« [-fpermissive]
../hid-libusb.c: In Funktion »void cleanup_mutex(void_)«:
../hid-libusb.c:982:20: Fehler: ungültige Umwandlung von »void_« in »hid_device_ 
{aka hid_device__}« [-fpermissive]
make: *_\* [qthid-cli] Fehler 1

But if I'm on the branch "qthid" I get these error if I do a make in the cli folder:

g++ `pkg-config libusb-1.0 --cflags` -I.. -Wall `pkg-config libusb-1.0 --libs` 
-o qthid-cli main.cpp ../fcd.c ../hid-libusb.c
../hid-libusb.c: In Funktion »hid_device\* hid_open_path(const char_)«:
../hid-libusb.c:784:10: Warnung: Variable »num_devs« gesetzt, aber nicht 
verwendet [-Wunused-but-set-variable]
/tmp/ccfhhLcD.o: In function `libusb_get_string_descriptor':
hid-libusb.c:(.text+0xad): undefined reference to`libusb_control_transfer'
/tmp/ccfhhLcD.o: In function `new_hid_device':
hid-libusb.c:(.text+0x120): undefined reference to`pthread_barrier_init'
/tmp/ccfhhLcD.o: In function `free_hid_device':
hid-libusb.c:(.text+0x139): undefined reference to`pthread_barrier_destroy'
/tmp/ccfhhLcD.o: In function `make_path':
hid-libusb.c:(.text+0x442): undefined reference to`libusb_get_device_address'
hid-libusb.c:(.text+0x450): undefined reference to `libusb_get_bus_number'
/tmp/ccfhhLcD.o: In function`hid_init':
hid-libusb.c:(.text+0x4cb): undefined reference to `libusb_init'
/tmp/ccfhhLcD.o: In function`hid_exit':
hid-libusb.c:(.text+0x52f): undefined reference to `libusb_exit'
/tmp/ccfhhLcD.o: In function`hid_enumerate':
hid-libusb.c:(.text+0x585): undefined reference to `libusb_get_device_list'
hid-libusb.c:(.text+0x5bc): undefined reference to`libusb_get_device_descriptor'
hid-libusb.c:(.text+0x5ed): undefined reference to 
`libusb_get_active_config_descriptor'
hid-libusb.c:(.text+0x610): undefined reference to`libusb_get_config_descriptor'
hid-libusb.c:(.text+0x709): undefined reference to `libusb_open'
hid-libusb.c:(.text+0x78f): undefined reference to`libusb_close'
hid-libusb.c:(.text+0x7f8): undefined reference to `libusb_free_config_descriptor'
hid-libusb.c:(.text+0x831): undefined reference to`libusb_free_device_list'
/tmp/ccfhhLcD.o: In function `read_callback':
hid-libusb.c:(.text+0xad1): undefined reference to`libusb_submit_transfer'
/tmp/ccfhhLcD.o: In function `read_thread':
hid-libusb.c:(.text+0xb1a): undefined reference to`libusb_alloc_transfer'
hid-libusb.c:(.text+0xb82): undefined reference to `libusb_submit_transfer'
hid-libusb.c:(.text+0xb90): undefined reference to`pthread_barrier_wait'
hid-libusb.c:(.text+0xb9f): undefined reference to `libusb_handle_events'
hid-libusb.c:(.text+0xbe6): undefined reference to`libusb_cancel_transfer'
hid-libusb.c:(.text+0xbfc): undefined reference to `libusb_handle_events'
/tmp/ccfhhLcD.o: In function`hid_open_path':
hid-libusb.c:(.text+0xc6e): undefined reference to `libusb_get_device_list'
hid-libusb.c:(.text+0xc8f): undefined reference to`libusb_get_device_descriptor'
hid-libusb.c:(.text+0xca1): undefined reference to 
`libusb_get_active_config_descriptor'
hid-libusb.c:(.text+0xd42): undefined reference to`libusb_open'
hid-libusb.c:(.text+0xd7d): undefined reference to `libusb_kernel_driver_active'
hid-libusb.c:(.text+0xda2): undefined reference to`libusb_detach_kernel_driver'
hid-libusb.c:(.text+0xdb8): undefined reference to `libusb_close'
hid-libusb.c:(.text+0xdea): undefined reference to`libusb_claim_interface'
hid-libusb.c:(.text+0xe0b): undefined reference to `libusb_close'
hid-libusb.c:(.text+0xf4a): undefined reference to`pthread_create'
hid-libusb.c:(.text+0xf58): undefined reference to `pthread_barrier_wait'
hid-libusb.c:(.text+0xfa2): undefined reference to`libusb_free_config_descriptor'
hid-libusb.c:(.text+0xfd8): undefined reference to `libusb_free_device_list'
/tmp/ccfhhLcD.o: In function`hid_write':
hid-libusb.c:(.text+0x108a): undefined reference to `libusb_control_transfer'
hid-libusb.c:(.text+0x10e0): undefined reference to`libusb_interrupt_transfer'
/tmp/ccfhhLcD.o: In function `hid_read_timeout':
hid-libusb.c:(.text+0x12bd): undefined reference to`clock_gettime'
/tmp/ccfhhLcD.o: In function `hid_send_feature_report':
hid-libusb.c:(.text+0x150a): undefined reference to`libusb_control_transfer'
/tmp/ccfhhLcD.o: In function `hid_get_feature_report':
hid-libusb.c:(.text+0x15b3): undefined reference to`libusb_control_transfer'
/tmp/ccfhhLcD.o: In function `hid_close':
hid-libusb.c:(.text+0x1604): undefined reference to`libusb_cancel_transfer'
hid-libusb.c:(.text+0x161a): undefined reference to `pthread_join'
hid-libusb.c:(.text+0x163f): undefined reference to`libusb_free_transfer'
hid-libusb.c:(.text+0x1656): undefined reference to `libusb_release_interface'
hid-libusb.c:(.text+0x1663): undefined reference to`libusb_close'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *_\* [qthid-cli] Fehler 1

73 de DL1MX
   Marco

www.qrz.com/db/DL1MX

Am 13.12.2012 20:01, schrieb tstranex:

> Hi Marco
> 
> Are you using the FCD Pro+ branch of my patch? I think I fixed the cast
> errors there.
> https://github.com/tstranex/qthid/tree/fcdpp
> 
> Regards,
> Timothy
>

**Comment by dl1mx** [comment]
Alex,

Sorry for the missunderstanding. Qthid is compiling fine, both versions (4.0, 
4.1). The problem is only the command line tool from Timothy that's in the pull 
request. I need the qthid-cli for the carpcomm software.

73 de DL1MX
   Marco

www.qrz.com/db/DL1MX

Am 13.12.2012 21:22, schrieb Alexandru Csete:

> Marco,
> 
> I don't understand your logic: Why do you think that a command line wrapper
> around qthid would solve your problem? You would still need to build qthid
> - some additional code.
> 
> Which version are you trying to compile? The hidraw backend has been the
> default for a long time now and most certainly is in version 4.0 and 4.1.
> Anyway, pretty much all versions of qthid should build without problem on
> all version of Ubuntu since 10.04, but I can't help you if you don't post
> any error messages. I recommend you try either the Funcube or FCD Pro+
> yahoo groups depending on which dongle you have.
> 
> Alex
>

**Comment by tstranex** [comment]
Hi Alex,

Ok, that sounds good. Is anyone actively working on libfcd? I may have a
bit of time to help with that in the next weeks.

Timothy

**Comment by csete** [comment]
Yes, we are working on libfcd. I'm currently trying to come up with the best way to include support for the Pro+ so that it can be more or less transparent to the application.

**Pull request closed without merging**
